export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST' 
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS' 
export const FETCH_CATEGORY_FAILIOR = 'FETCH_CATEGORY_FAILIOR' 

export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'

export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST' 
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS' 
export const FETCH_PRODUCT_FAILIOR = 'FETCH_PRODUCT_FAILIOR'