//CATEGORY TYPE
export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST' 
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS' 
export const FETCH_CATEGORY_FAILIOR = 'FETCH_CATEGORY_FAILIOR' 

export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'

// PRODUCT TYPE
export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST' 
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS' 
export const FETCH_PRODUCT_FAILIOR = 'FETCH_PRODUCT_FAILIOR'

//CART  Type

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREACE_QUANTITY_OF_PRODUCT = "INCREACE_QUANTITY_OF_PRODUCT";
export const DECREACE_QUANTITY_OF_PRODUCT = "DECREACE_QUANTITY_OF_PRODUCT";
